# Generated by Django 5.2rc1 on 2025-04-01 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_property_propertyimage_propertyinquiry_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='property',
            name='category',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_balcony',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_elevator',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_garden',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_parking',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_furnished',
        ),
        migrations.RemoveField(
            model_name='property',
            name='minimum_rental_period',
        ),
        migrations.RemoveField(
            model_name='property',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='property',
            name='security_deposit',
        ),
        migrations.RemoveField(
            model_name='property',
            name='ward_number',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('land', 'Land'), ('commercial', 'Commercial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented')], default='available', max_length=20),
        ),
        migrations.DeleteModel(
            name='PropertyInquiry',
        ),
    ]
