# Generated by Django 5.2rc1 on 2025-04-15 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_propertyview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertyview',
            unique_together={('property', 'user')},
        ),
        migrations.AddField(
            model_name='propertyview',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.RemoveField(
            model_name='propertyview',
            name='ip_address',
        ),
    ]
