# Generated by Django 5.2rc1 on 2025-04-15 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_propertyview_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertyview',
            unique_together=set(),
        ),
    ]
