# Generated by Django 5.2rc1 on 2025-04-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_propertyview_unique_together'),
    ]

    operations = [
    ]


