# Generated by Django 5.2rc1 on 2025-04-15 01:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_duplicate_property_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertyview',
            unique_together={('property', 'user')},
        ),
    ]
