# Generated by Django 5.1.1 on 2025-04-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_propertyview_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('kathmandu', 'Kathmandu'), ('pokhara', 'Pokhara'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur')], max_length=100),
        ),
    ]
